config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :events
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "events#index"
  resources :invitations, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  belongs_to :user, optional: true

  has_many :invitations, foreign_key: :attended_event_id
  has_many :attendees, through: :invitations, source: :attendee

  scope :prev_events, -> { where('datetime < ?', Date.current) }
  scope :next_events, -> { where('datetime >= ?', Date.current) }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/invitations.rb
class Invitations < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  validates :email, presence: true

  has_many :events, foreign_key: :user_id

  has_many :invitations, foreign_key: :attendee_id
  has_many :attended_events, through: :invitations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  # GET /events or /events.json
  def index
    @events = Event.all
    @prev_events = Event.prev_events
    @next_events = Event.next_events
  end

  # GET /events/new
  def new
    @event = current_user.events.build
  end

  # POST /events or /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:title, :body, :datetime)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def create
    event_id = params[:event_id]
    @attendee = Invitation.find_or_initialize_by(attendee_id: current_user.id, attended_event_id: event_id)
    if @attendee.save
      flash[:notice] = 'Now you attended to this event.'
    else
      flash[:alert] = 'Something wrong happened'
    end
    redirect_to root_path
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def edit
    @all_events = Event.where(user_id: current_user)
    @prev_events = current_user.events.prev_events
    @next_events = current_user.events.next_events
  end

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def update_account_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_notice
    render inline: '<div class="notification"><p class="notice"><%= notice %></p></div>'.html_safe if flash[:notice]
  end

  def flash_alert
    render inline: '<div class="notification"><p class="alert"><%= alert %></p></div>'.html_safe if flash[:alert]
  end

  def nav_bar(var)
    if var
      render inline: '
      <div class="button">
        <%= link_to "Profile", edit_user_registration_path %>
      </div>
      <div class="button">
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      </div>'.html_safe
    else
      render inline: '
      <div class="button">
        <%= link_to "Sign Up", new_user_registration_path %>
      </div>
      <div class="button">
        <%= link_to "Sign In", new_user_session_path %>
      </div>'.html_safe
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def new_event(var)
    render inline: '<%= link_to "New Event", new_event_path, class: "new-event" %>' if var
  end

  def show_member(var)
    if var
      render inline: '<h3>No members in this event!</h3>'.html_safe
    else
      @event.attendees.map { |item| tag.p(item.name) }.join.html_safe
    end
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
  def invitation(var)
    if var
      render 'invitations/invitation', event: @event
    else
      render inline: '<h3>To attend this event you need to log in!</h3>'.html_safe
    end
  end
end

app/views/events/_event.html.erb
<div class="extra">
  <div>
    <h1><%= event.title %></h1>
  </div>
  <hr/>
  <div>
    <h3>Date:</h3>
    <%= event.datetime%>
  </div>
  <div>
    <h3>Owner:</h3>
      <%= event.user.name %>
  </div>
  <div>
    <h3>Email:</h3>
    <%= event.user.email %>
  </div>
  <hr/>
  <div class="show-button">
    <%= link_to 'Show', event, class: 'button' %>
  </div>
</div>

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
    <%= f.input :datetime %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/events/_next_event.html.erb
<div class="extra">
  <div>
    <h1><%= event.title %></h1>
  </div>
  <hr/>
  <div>
    <h3>Date:</h3>
    <%= event.datetime%>
  </div>
  <div>
    <h3>Owner:</h3>
      <%= event.user.name %>
  </div>
  <div>
    <h3>Email:</h3>
    <%= event.user.email %>
  </div>
  <hr/>
  <div class="show-button">
    <%= link_to 'Show', event, class: 'button' %>
  </div>
</div>

app/views/events/_prev_event.html.erb
<div class="extra">
  <div>
    <h1><%= event.title %></h1>
  </div>
  <hr/>
  <div>
    <h3>Date:</h3>
    <%= event.datetime%>
  </div>
  <div>
    <h3>Owner:</h3>
      <%= event.user.name %>
  </div>
  <div>
    <h3>Email:</h3>
    <%= event.user.email %>
  </div>
  <hr/>
  <div class="show-button">
    <%= link_to 'Show', event, class: 'button' %>
  </div>
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<%= new_event(user_signed_in?) %>

<br/ >
<hr style="position: relative; top: 5px;"/>
<h2>Previous Events</h2>
<div class="grid">
  <%= render @prev_events %>
</div>

<h2>Upcoming Events</h2>
<div class="grid">
  <%= render @next_events %>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<div class="show-event">
  <p>
    <strong>Title:</strong><br/>
    <%= @event.title %>
  </p>
  <p>
    <strong>Description:</strong><br/>
    <%= @event.body %>
  </p>
  <p>
    <strong>Datetime:</strong><br/>
    <%= @event.datetime %>
  </p>
  <div>
    <h3>Owner:</h3>
    <%= @event.user.name %>
  </div>
  <div>
    <h3>Email:</h3>
    <%= @event.user.email %>
  </div>
  <hr/>

  <%= invitation(user_signed_in?) %>

  <div>
    <h2>List of members</h2>
    <%= show_member(@event.attendees.empty?) %>
  </div>
</div>

app/views/invitations/_invitation.html.erb
  <%= form_with(model: @invitation, url: invitations_path, method: 'POST', local: true) do |form| %>
    <div class="">
      <%= form.hidden_field :event_id, class: '', value: event.id %>
      <div>
        <%= form.submit 'Attend Event' %>
      </div>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicketingPlatform</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash_notice() %>
    <%= flash_alert() %>
    <div style="display: flex;">
      <div class="button">
        <%= link_to 'Home', root_path %>
      </div>
      <%= nav_bar(user_signed_in?) %>
    </div>

    <%= yield %>
  </body>
</html>